### ISSUE TITLE
RealSumTest failure on MacbookPro 10,1 (Retina, Mid 2012)

### ISSUE THREAD

**Issue by jni** [imglib/imglib2#192]
When I run:

```
git clone git@github.com:imglib/imglib2
cd imglib2
mvn clean install
```

On my Macbook (2017), everything works fine, but on my Macbook Pro 10,1 (Retina, Mid 2012), I get a single test failure:

```
Running net.imglib2.util.RealSumTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.7 sec <<< FAILURE! - in net.imglib2.util.RealSumTest
testAdd(net.imglib2.util.RealSumTest)  Time elapsed: 0.016 sec  <<< FAILURE!
java.lang.AssertionError: expected:<934464.0> but was:<1000000.0>
	at net.imglib2.util.RealSumTest.testAdd(RealSumTest.java:122)
```

Git commit is 8bc4372b741b195ba8a47819f9bc9f9673778f80

Both laptops are running macOS 10.13.1 High Sierra, so it might actually be processor-dependent.

**Comment by axtimwalde** [comment]
This error is not related to this commit.  `RealSum` does not work at the expected precision on this 2012 Mac which means that double precision means something less precise for this machine than for others which is surprising because both machines sport Intel processors---correct?  `RealSum` is meant to exceed double precision for large sequences of limited size numbers but uses double precision calculations internally.  You can skip the test with `mvn -DskipTests`.  Otherwise, this is a bug in the Java distribution for this MacOS version, not sure how relevant because on an old machine.

**Comment by jni** [comment]
Sorry I didn’t mean to imply that the commit caused it — just that this was the head commit at the time that I cloned the repo, and thus the commit that I was testing. 

Both processors are 64-bit intel. I can check java builds tomorrow. Skipping the tests is probably a sufficient fix for me. =) Feel free to close if this seems irrelevant.

**Comment by ctrueden** [comment]
What does `mvn -v` say on each of the two machines? Any differences?

**Comment by jni** [comment]
@ctrueden here's the output on Macbook 2017:

```
jni@molino Tue Dec 05 09:45
 ~/projects/imglib2 (master)
 $ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T03:41:47+11:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_AU, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"
```

Maven is the same but the Java build is much older on the Macbook Pro, 1.8.0_25. I'll update Java and see if the error still persists.

**Comment by jni** [comment]
Yep, updating Java fixed the problem, so @axtimwalde's hunch that it was a bug in Java appears to have been correct. Incidentally, is there a way for POM files to specify a minimum Java version? This is the second time a Java version issue has bitten me in the ass in as many days.

**Comment by ctrueden** [comment]
> Incidentally, is there a way for POM files to specify a minimum Java version?

There is now! scijava/pom-scijava-base@54bf6664462db3cb538a39986005ac91bded13d5

See [here](https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html) for documentation on the format of the version string. 

Once this change is released and propagates downstream, we can add minimum Java requirements to projects that need it by overriding the `scijava.jvm.build.version` property.

**Comment by jni** [comment]
Hahahahaha thanks for the dedication! I love it.

For my own clarification, this problem was caused not by a major/minor version change, but rather by a... build number? Not sure what the stuff after the underscore is technically. Does this POM format support build numbers? Are those even meaningful cross-platform?

**Comment by ctrueden** [comment]
@jni Yeah, it seems there was a bug in Java, still present in 1.8.0_25, but fixed by 1.8.0_151. In my understanding, the suffix after the underscore is not a "build number" per se, but a patch release with bugs fixed. I am not actually sure under what circumstances the OpenJDK project would release 1.8.1... with 1.6 and 1.7, there was never anything past point zero.

I was able to reproduce that 1.8.0_11 (unsurprisingly) fails, but 1.8.0_45 succeeds.

> Does this POM format support build numbers? Are those even meaningful cross-platform?

Yep, the documentation I linked above describes how these numbers get standardized. If by "cross-platform" you mean across OS platforms, then yes, I think it is meaningful. I am less certain about alternative implementations of the JVM besides OpenJDK or Oracle, but those are the two we officially support, so I'm comfortable adding a minimum requirement on 1.8.0_45 for now. And here it is: 156d365aa3b5aa2a7df897532469bc99fd9f037d.

Be aware that this won't actually enforce that minimum version until the POM is updated to extend a new release of pom-scijava-base; see imglib/pom-imglib2#1. @tpietzsch maybe we can take care of that during the hackathon?

**Comment by jni** [comment]
> If by "cross-platform" you mean across OS platforms, then yes, I think it is meaningful. 

Yes, I am using conda versions as my conceptual baseline, where typically things after the underscore are build numbers that might be platform- and even compiler-dependent and don't necessarily port between OSs.

> this won't actually enforce that minimum version until the POM is updated to extend a new release of pom-scijava-base

Coolio. https://github.com/saalfeldlab/bigcat might also need updating? Earlier this week I [needed 1.8.0_101](http://forum.imagej.net/t/https-to-make-imagej-fiji-more-secure/398/11) to be able to resolve its dependencies. As mentioned in the linked thread (thanks to @hanslovsky for the tip), even just a meaningful error that gets users to update Java would be very useful.

**Comment by ctrueden** [comment]
> https://github.com/saalfeldlab/bigcat might also need updating?

Care to file a PR? Modeled after 156d365aa3b5aa2a7df897532469bc99fd9f037d. Hopefully @axtimwalde likes this.

> even just a meaningful error that gets users to update Java would be very useful.

Completely agreed.

**Comment by jni** [comment]
@ctrueden 

Does that commit have a typo? 1.8.0-45 vs 1.8.0_45?

**Comment by ctrueden** [comment]
> Does that commit have a typo? 1.8.0-45 vs 1.8.0_45?

No, the version is standardized according to the enforcer's processing scheme, outlined [here](https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html).
