### ISSUE TITLE
Bug in StackView

### ISSUE THREAD

**Issue by tischi** [imglib/imglib2#253]
@tpietzsch 
In StackView there is this line of code (https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/view/StackView.java#L237):
```
sliceAccesses = Util.genericArray( a.sliceAccesses.length );
```
In one of my code it is going there and I am getting an error: Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.imglib2.RandomAccess;
I just reproduced that with a very simple test:
```
public static void  main( String[] args )
{
    final RandomAccess[] objects = Util.genericArray( 2 );
}
```
which also gives me that error. I am confused now, whether this particular line of code in StackView is just not working or whether I have to look for a bug in my code somewhere else.
Here is the link to the genericArray function that is called: https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/util/Util.java#L75

**Comment by tischi** [comment]
This works for me! Thanks! 

I would then compile this branch as version `5.7.1` and upload it to my update site. Do you think this is OK? 

Because, as you probably know, I learned recently that everybody using my update site will then have version `5.7.1` of imglib2 for everything (as there is only one version of each library in Fiji).

**Comment by tpietzsch** [comment]
I'll merge it to master now, then make a proper release. You can put that on your update site. You just have to remember to take it off again, when the imglib2 version shipped with Fiji supersedes it.

**Comment by ctrueden** [comment]
> I would then compile this branch as version 5.7.1

I would not recommend changing any version numbers. Just build the code at the commit you want, and it'll come out as a SNAPSHOT (rightly so), and you can—if desired—ship that SNAPSHOT on your update site.

If/when @tpietzsch cuts a release, you can of course ship that release build (downloaded from maven.scijava.org either directly or via Maven from the command line). But there is no requirement that your update site ship only release builds. Every SNAPSHOT build has the commit hash at which it was built baked inside, so code provenance is traceable.

**Comment by tpietzsch** [comment]
@ctrueden That is exactly what I was too lazy to write, and instead thought "...whatever, I just cut a release quickly"

**Comment by tpietzsch** [comment]
of course the release fails now... serves me right

**Comment by tpietzsch** [comment]
@tischi I releases imglib2-5.8.0

**Comment by tischi** [comment]
@ctrueden 
...but there was this issue the SciJava maven enforcer rules would not let me include SNAPSHOT dependencies: https://forum.image.sc/t/snapshot-dependency/26292
That's why I was wondering how to use the fix. 
But if Tobi makes a proper release that's anyway the best, I guess.

**Comment by tpietzsch** [comment]
@tischi If it is something like this where the API doesn't change, you could just compile against the older version and still ship the SNAPSHOT on the update site.

**Comment by tischi** [comment]
Ok, but I still do not understand how that would work with the current SciJava maven enforcer rules (see above).

**Comment by tpietzsch** [comment]
In this case it would work like this: You put imglib2 version 5.7.0 (no SNAPSHOT) into the pom. You put imglib2-5.7.1-SNAPSHOT.jar on your update site. The version you build against (in the pom) and the version you use at runtime (on the update site) don't have to match.

But now there is 5.8.0 released, so ...

**Comment by imagejan** [comment]
@tischi wrote:
> ...but there was this issue the SciJava maven enforcer rules would not let me include SNAPSHOT dependencies: forum.image.sc/t/snapshot-dependency/26292

The forum topic you linked is exclusively about maven, not about the updater, right? While running `mvn` will complain if you have SNAPSHOT dependencies, the ImageJ updater doesn't care. Building with Maven and uploading with the updater are two different things.

The only thing connecting them (and which you probably had in mind, I guess) is when you run:

```
mvn -Dscijava.app.directory=/path/to/Fiji.app
```

... this indeed won't work with SNAPSHOT dependencies, but nothing stops you to copy the SNAPSHOT into your Fiji installation manually and then using the ImageJ updater to upload the artifact.

**Comment by tischi** [comment]
I see! It did not occur to me that my pom and the version in the Fiji.app folder could be different. Thanks for the clarification!

**Comment by ctrueden** [comment]
> It did not occur to me that my pom and the version in the Fiji.app folder could be different. 

In an ideal world, they would not have to be. Because when they _are_ different, then people may encounter different behavior when running inside Fiji as an end user, versus running from an IDE as a developer. This is a bad thing, in general. We have worked very hard toward unifying Fiji so that the Fiji application has the same stuff as the fiji/fiji repository on GitHub. See also [fiji/fiji#39](https://github.com/fiji/fiji/issues/39), [fiji/fiji#38](https://github.com/fiji/fiji/issues/38), [fiji/fiji#37](https://github.com/fiji/fiji/issues/37).

At hackathons we have discussed making the Updater more closely tied to Maven repositories and/or POMs, but there are always exceptions where you may want to ship a JAR or resources outside the context of Maven. For example, some people do not want to (or cannot) use Maven but instead are developing using other tools, and it is good that they can still ship their stuff on ImageJ update sites.

@tischi The question for you is: for each end-user update site configuration you ship: do you care about there being a specific tag (or even commit) on GitHub corresponding to that configuration? By shipping a SNAPSHOT as discussed above, you are creating an end-user configuration without a corresponding source configuration—in a nutshell, "admitting open source defeat." This is (very gently, in this particular case) against the open source spirit. It's up to you whether that bothers you.

Personally, I almost never upload SNAPSHOTs, unless the bug-fix being delivered is absolutely time-critical for users. And then I replace it with a release version as soon as possible. I also think the barrier to creating release versions needs to be as low as possible, to avoid the need for shipping SNAPSHOTs in the first place.
