### ISSUE TITLE
Move Mines derived FFT code out of algorithms-gpl?

### ISSUE THREAD

**Issue by bdezonia** [imglib/imglib2#38]
I would like to use the FFT code in Imglib2 in some IJ2 plugins. As they stand they exist in algorithms-gpl and thus can't be used. They use the Mines Java Toolkit.

I checked the Mines Java Toolkit and it is licensed under the CPL. Maybe it was GPL at one time but no longer. I contacted the author and he says we can use the jar in any BSD project. We cannot modify/distribute the source of Mines as anything but CPL.

This sounds to me like there is no reason for the various Mines derived FFT classes to live in algorithms-gpl (when instead it could possibly move to plain algorithms project).

Does the person who decided to put it in algorithms-gpl want to weigh in here? Or anyone else with an opinion?

**Comment by ctrueden** [comment]
I believe this issue is long resolved. The [imglib2-algorithm-fft](https://github.com/imglib/imglib2-algorithm-fft) project (licensed BSD-2) has FFT code in `net.imglib2.algorithm.fft2.FFTMethod` that uses Mines JTK. And [imglib2-algorithm-gpl](https://github.com/imglib/imglib2-algorithm-gpl) (licensed GPLv2+) has additional FFT code in `net.imglib2.algorithm.fft.FFTFunctions`, `net.imglib2.algorithm.fft.FourierTransform` and `net.imglib2.algorithm.pde.MomentOfInertiaTensor3D` which also uses Mines JTK. I believe this structure properly reflects the wishes of the various ImgLib2 authors, as discussed above.

There was a license incompatibility between Mines JTK (licensed CPL) and the GPLv3, but that is now resolved due to Mines JTK's switch to APLv2.

**Comment by StephanPreibisch** [comment]
Great!
